spring:
  r2dbc:
    url: r2dbc:mysql://thomas.proxy.rlwy.net:40415/bankguard_auth
    username: root
    password: ${MYSQL_PASSWORD}

  cloud:

    gateway:

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns:
              - "http://localhost:*"
              - "https://bank-gaurd-frontend.vercel.app"
              - "https://bank-gaurd-customer.vercel.app"

            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS

            allowedHeaders:
              - "*"

            exposedHeaders:
              - "*"

            allowCredentials: false

      server:
        webflux:

          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

          routes:

            - id: transaction-service
              uri: lb://transactionService
              predicates:
                - Path=/api/transactions/**

            - id: customer-service
              uri: lb://transactionService
              predicates:
                - Path=/api/customers/**

            - id: enrichment-service
              uri: lb://enrichmentService
              predicates:
                - Path=/api/enrich/**

            - id: decision-engine-service
              uri: lb://decision-engine-service
              predicates:
                - Path=/api/gemini/**

            - id: alertcase-service
              uri: lb://alert-case-service
              predicates:
                - Path=/api/investigation/**

            - id: sar-service
              uri: lb://sarReport
              predicates:
                - Path=/sar/**

eureka:
  client:
    service-url:
      defaultZone: https://eureka-server-ku09.onrender.com/eureka/
    fetch-registry: true
    register-with-eureka: true

  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: INFO
